### PR TITLE
Simplify escape_examples()

### LINKED ISSUE #967: incorrect use of backslashes in .Rd files
The latest version (7.0.0) breaks one of my `.Rd` files containing the following code in an example:

```
paths <- list("./aaa/zzz",
              "./aaa/zzz/",
              ".//aaa//zzz",
              ".//aaa//zzz/",
              ".\\aaa\\zzz",
              ".\\aaa\\zzz\\", ## <- the double backslashes should convert to quad-backslashes
              file.path(".", "aaa", "zzz"))
```

gets converted to this in the `.Rd`:

```
paths <- list("./aaa/zzz",
              "./aaa/zzz/",
              ".//aaa//zzz",
              ".//aaa//zzz/",
              ".\\\\aaa\\\\zzz",
              ".\\\\aaa\\\\zzz\\\", ## <- note the 3 trailing backslashes instead of 4
              file.path(".", "aaa", "zzz"))
```

this has the effect of escaping the closing quotation mark, which results in the warning

```
Warning: newline within quoted string 
```

As a workaround, I have commented out the offending line in the example, but this is a temporary solution.
https://github.com/PredictiveEcology/reproducible/commit/fbf8bf68d8efcab844214d13542261a02303e605

### PR DESCRIPTION
**Pull request by hadley**
Fixes #967

### CODE REVIEW

File: R/rd-examples.R [hunk 1]
```diff
@@ -37,29 +37,39 @@ format.rd_section_examples <- function(x, ...) {
...
+#'
+#' # Otherwise, backslashes and braces can be left as is
+#' "\""
+#' "{"
+#' # It looks like you could use Rd tags in comments, but these are
+#' # not actually parsed
+#' 1 # \link{mean}
+#'
+#' # The only place that a backslash can occur in R code is as part of
+#' # an infix operator. If you do that, you'll need to escape yourself.
```
Comment (gaborcsardi) [inline R/rd-examples.R]: Strictly speaking it can occur in any symbol, I think:
```r
❯ `\\` <- 10
❯ ls()
[1] "\\"
```
